version: '3'

services:
  src:
    image: src
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    volumes:
      - ./src/appsettings.Production.json:/app/appsettings.Production.json
      - ./src/wwwroot/uploads/:/app/wwwroot/uploads/
    environment:
      ASPNETCORE_URLS: "http://localhost:5000"
      ASPNETCORE_ENVIRONMENT: "Production"
    command: ["dotnet", "src.dll"]
